php-fpm: Make service reload/restart configurable
voxpupuli/puppet-php pull request #598
Opened 2020-08-29 06:57 UTC by bastelfreak

By default, this module uses a reload for the php-fpm service. This is
nice because it ensures that there is no downtime. But this is also bad
because certain configuration options, like unix socket owner/group will
only be changed during a restart.

Fixes: https://github.com/voxpupuli/puppet-php/issues/596
Replaces: https://github.com/voxpupuli/puppet-php/pull/597

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2020-08-29 08:42 UTC, c33s approved these changes
lgtm

2020-09-01 07:14 UTC, igalic requested changes
👀

2020-09-01 07:14 UTC, igalic commented on manifests/fpm.pp
> +#   This default should be changed in a future release.
should be ➡️ will be

2020-09-01 07:14 UTC, igalic commented on manifests/init.pp
> +#   This default should be changed in a future release.
should be ➡️ will be

2020-09-01 07:14 UTC, igalic commented on manifests/fpm/service.pp
> +#   This default should be changed in a future release.
should be ➡️ will be

2020-09-02 18:25 UTC, bastelfreak commented on manifests/fpm/service.pp
> +#   This default should be changed in a future release.
fixed

2020-09-02 18:25 UTC, bastelfreak commented on manifests/init.pp
> +#   This default should be changed in a future release.
fixed

2020-09-02 18:25 UTC, bastelfreak commented on manifests/fpm.pp
> +#   This default should be changed in a future release.
fixed

2020-09-02 18:26 UTC, merged