Adding class parameter fpm_log_dir_mode to customize the file permission of log directory
voxpupuli/puppet-php pull request #675
Opened 2022-12-13 13:31 UTC by Q-Storm

#### Pull Request (PR) description

I created the PR to parametrize the file permission for the php-fpm log directory.

#### This Pull Request (PR) fixes the following issues

2022-12-14 08:01 UTC, kenyon requested changes
Would be nice to also add a test to https://github.com/voxpupuli/puppet-php/blob/master/spec/classes/php_spec.rb

2022-12-14 13:57 UTC, jnk0 commented
Also mentioned in #523.

2022-12-19 07:53 UTC, Q-Storm commented
> Would be nice to also add a test to https://github.com/voxpupuli/puppet-php/blob/master/spec/classes/php_spec.rb

This is my first rspec test. I hope the test is as expected.

2022-12-19 08:01 UTC, Q-Storm commented on manifests/init.pp
> +  Pattern[/^\d+$/] $fpm_log_dir_mode              = $php::params::fpm_log_dir_mode,
I implemented the changes a suggested. Nice to know that stdlibs covers this.

2022-12-19 17:47 UTC, kenyon approved these changes

2023-07-13 20:33 UTC, smortex approved these changes

2023-07-13 20:33 UTC, merged